name: smartcharge_app
description: "Simulatore e monitoraggio ricarica veicoli elettrici."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  shared_preferences: ^2.5.4
  uuid: ^4.5.1
  intl: ^0.19.0
  fl_chart: ^0.70.0
  pdf: ^3.10.8
  printing: ^5.11.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Assicurati che il file cars.json sia fisicamente nella cartella 'assets' 
  # alla radice del tuo progetto MacBook.
  assets:
    - assets/cars.json
    - assets/logo.png