name: smartcharge_app
description: "Simulatore e monitoraggio ricarica veicoli elettrici."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  shared_preferences: ^2.5.4
  uuid: ^4.5.1
  

  # Libreria per la gestione delle date e formattazione oraria
  intl: ^0.19.0
  
  # Libreria per i grafici (BarChart e LineChart)
  fl_chart: ^0.70.0
  

  # Icone aggiuntive stile iOS (opzionale ma consigliato)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cars.json
  # Se in futuro vorrai aggiungere icone personalizzate o immagini, 
  # dovrai decommentare le righe qui sotto:
  # assets:
  #   - assets/images/
